### ISSUE TITLE
Fails to locate URI different from base-URI

### ISSUE THREAD

**Issue by lucasmauricio** [auyer/FastGate#2]
FastGate fails to redirect requests that have URI different from the base-uri (its database key):

It works when I try `localhost:8080/api/myservice` with the service registered as `api/myservice`.
But it doesn't work when I try to request `localhost:8080/api/myservice/44`: I got 404 with the message _Key not found_.

**Comment by auyer** [comment]
Problem solved in release 0.2
Thanks for the feedback!
